### ISSUE TITLE
No Variable Window Extensions

### ISSUE THREAD

**Issue by BillBoroson** [BIDeveloperExtensions/bideveloperextensions#105]
I'm using version 2.3.9 of BI Developer Extensions with Visual Studio 2017 (v. 15.9.23).  My issue is that I don't see the SSIS Variables Window Extensions while building SSIS packages.  However, the SSIS Parameter Window Extensions do appear as well as other functionality of BI Developer Extensions.  How can I get the variable window extensions to appear?

**Comment by BillBoroson** [comment]
I upgraded to the latest version of SSDT (15.9.25) hoping that it would fix this issue but it didn't help.

**Comment by furmangg** [comment]
Can you screenshot the Tools... Options... BIDS Helper... Version tab please

**Comment by BillBoroson** [comment]
Here's the screenshot...
![BH Version Screenshot](https://user-images.githubusercontent.com/18312540/89578980-ff1e5900-d800-11ea-819f-9f43e940df41.png)

**Comment by debdicken** [comment]
I am having this same issue. Here are the versions I have installed:
![BIVersions](https://user-images.githubusercontent.com/34750797/90411216-48bc3e80-e060-11ea-8856-cdacde54f1e4.jpg)

**Comment by furmangg** [comment]
We released BI Developer Extensions 2.4.0. This should specifically fix your issue 

@BillBoroson you seem to have a recent SSDTBI build (15.0.1659.0). If this doesn't fix your issue, I would recommend installing the SSAS extension since we have limited time to test each feature under each combination of SSAS/SSIS/SSRS being installed or not installed.

@debdicken If the latest BI Developer Extensions doesn't fix it, your SSDTBI build number (15.0.900.163) is quite a bit out-of-date. We've uploaded the [download instructions](https://bideveloperextensions.github.io/downloads/) to indicate that you may need to uninstall and reinstall in order to get to a newer SSDTBI build number (the shared modules that can't be updated directly).
