### ISSUE TITLE
SSIS: Error on opening package

### ISSUE THREAD

**Issue by wim-dp** [BIDeveloperExtensions/bideveloperextensions#106]
**Describe the bug**
On opening a package deployement dtsx package, an error occurs. 
Unable to cast object of type 'Microsoft.DataTransformationServices.Design.DtsPackageView' to 'Microsoft.DataWarehouse.Design.EditorWindow'. 
at BIDSHelper.SSIS.ParamatersWindowPlugin.OnWindowActivated

Deploy button is also not visible

![image](https://user-images.githubusercontent.com/57260437/89797411-348db400-db2b-11ea-9859-8554552823be.png)

**Version**
![image](https://user-images.githubusercontent.com/57260437/89798110-11afcf80-db2c-11ea-82d0-90143d1661d8.png)

**To Reproduce**
1. Go to Solution Explorer
2. Click on any .dtsx package
3.  See error

**Expected behavior**
No error 
Deploy button should be visible 
![image](https://user-images.githubusercontent.com/57260437/89797899-cc8b9d80-db2b-11ea-8e70-a6e90eeee748.png)

**Additional context**
Updated to SSDT BI to 15.9.25 
![image](https://user-images.githubusercontent.com/57260437/89798047-f5ac2e00-db2b-11ea-8e07-f30395d4dbae.png)

**Comment by furmangg** [comment]
We released BI Developer Extensions 2.4.0. This should specifically fix your issue. If it doesn't your SSDTBI build number (15.0.1200.70) is quite a bit out-of-date. We've uploaded the [download instructions](https://bideveloperextensions.github.io/downloads/) to indicate that you may need to uninstall and reinstall in order to get to a newer SSDTBI build number (the shared modules that can't be updated directly).
