### ISSUE TITLE
Deploy MDX Script - Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by ea25** [BIDeveloperExtensions/bideveloperextensions#107]
Getting Object reference not set to an instance of an object when I try to deploy mdx script.

Using Visual Studio 2017 Version 15.9.12 with  BIDS Helpver version 2.3.9.0.

Can someone point where can I start investigating this ?

**Comment by furmangg** [comment]
Can you post a screenshot from the Tools...Options... BIDS Helper... Version screen?

**Comment by ea25** [comment]
Please find attached below.

![image](https://user-images.githubusercontent.com/25198590/90336021-5975a180-dfd9-11ea-9105-68763d5d9dd2.png)

**Comment by furmangg** [comment]
Thank you for reporting. I was able to reproduce in Visual Studio 2017 (not Visual Studio 2019 for some reason) and have a fix for this specific issue coded. I'm going to do some more thorough testing before I release this fix, probably later this week.

**Comment by ea25** [comment]
Much appreciated. Please note I'm also experiencing this on VS 2017, didn't have any problems on VS 2019 - same situation as yours.

**Comment by AgentRatty** [comment]
Furmangg, I am experiencing this issue with VS 2019 on SQLServer 2019. Upon trying to "Deploy MDX Script" I get "Object reference not set to an instance of an object."

![image](https://user-images.githubusercontent.com/28762569/91771988-d20f5d00-eb98-11ea-8c63-4da384a31e1c.png)

**Comment by furmangg** [comment]
We released BI Developer Extensions 2.4.0. But based upon your version numbers you are significantly out-of-date. 

@AgentRatty your SSDTBI build is 15.0.1200.70 which is quite out-of-date. We've uploaded the [download instructions](https://bideveloperextensions.github.io/downloads/) to indicate that you may need to uninstall and reinstall in order to get to a newer SSDTBI build number (the shared modules that can't be updated directly). If that still doesn't fix it, go ahead and install the SSIS extension. We do the best we can to ensure individual features work without unrelated extensions, but we have limited time to test without SSRS/SSAS/SSIS all being installed.

@ea25 your SSDTBI build is 15.0.1000.59 which is quite out of date. Use the download instructions link above to uninstall and reinstall. 

After you do that BI Developer Extensions 2.4 should fix your problems.
