### ISSUE TITLE
Parent-Child Dimension Naturalizer throws error

### ISSUE THREAD

**Issue by JoelCottage** [BIDeveloperExtensions/bideveloperextensions#108]
Can not get past first screen of the Parent-Child Dimension Naturalizer.  Will throw error:  
![image](https://user-images.githubusercontent.com/40039492/90541318-6f59a280-e150-11ea-9cb3-f13a62ff5f76.png)

**Version**
Visual Studio Professional 2017 Version 15.9.26
![image](https://user-images.githubusercontent.com/40039492/90541385-8ac4ad80-e150-11ea-9ab3-067642e6212d.png)

**To Reproduce**
1. Right click dimension > Parent-Child Dimension Naturalizer...
2. Make selections
3. Click OK

**Comment by furmangg** [comment]
Thanks for reporting. We seem to be having some pretty significant SSAS feature compatibility issues in VS2017. So far VS2019 seems to be working fine if you need a temporary workaround. Will keep this thread posted as we get to the bottom of the issues in VS2017.

**Comment by furmangg** [comment]
We released BI Developer Extensions 2.4.0. This should hopefully fix your issue. If it doesn't your SSDTBI build number (15.0.1200.70) is quite a bit out-of-date. We've uploaded the [download instructions](https://bideveloperextensions.github.io/downloads/) to indicate that you may need to uninstall and reinstall in order to get to a newer SSDTBI build number (the shared modules that can't be updated directly).

Please test and confirm this fixes your issue. If it doesn't let me know and we can reopen.
