### ISSUE TITLE
Calculation Properties (BIDS Helper) Unable to cast object type

### ISSUE THREAD

**Issue by AgentRatty** [BIDeveloperExtensions/bideveloperextensions#110]
SQL Server 2019, VS 2019

Upon trying to set or edit calculation properties, dialog pops up with following error:

![image](https://user-images.githubusercontent.com/28762569/91772647-26ffa300-eb9a-11ea-9194-3bfaea9a1150.png)

![image](https://user-images.githubusercontent.com/28762569/91772844-7f36a500-eb9a-11ea-836e-84df3d617188.png)

**Comment by furmangg** [comment]
We released BI Developer Extensions 2.4.0. This should specifically fix your issue. If it doesn't your SSDTBI build number (15.0.1200.70) is quite a bit out-of-date. We've uploaded the [download instructions](https://bideveloperextensions.github.io/downloads/) to indicate that you may need to uninstall and reinstall in order to get to a newer SSDTBI build number (the shared modules that can't be updated directly).

**Comment by AgentRatty** [comment]
Thanks, it worked without having to update my SSDTBI build since the marketplace indicated an update for BIDE 2.4.0

![image](https://user-images.githubusercontent.com/28762569/91889077-17d43000-ec42-11ea-87ae-148c5f78c961.png)

Thanks!

AR
