### ISSUE TITLE
Cannot Remove BIDSHelper

### ISSUE THREAD

**Issue by ylax** [BIDeveloperExtensions/bideveloperextensions#16]
Hi, I installed the BIDSHelper VS add-on for VS2015 and it started causing my VS to lock up every time I right-clicked in solution explorer. So, I attempted to remove it first using the extensions manager (which didn't remove it completely) then actually trying to hunt down all the different components and manually deleting them. There are apparently still some components left on my machine and they are still causing VS to screw up. This is the case even after I've done a complete reinstall of VS. Please advise exactly where you install all these components and how you register them with VS so I can truly remove your software from my computer.

Thank you. -yl

**Comment by furmangg** [comment]
The VSIX installer model is pretty awesome. The installer puts it in an isolated user folder. After you uninstall BI Developer Extensions and close all Visual Studio instances it will delete the files. I have never run into an issue where it didn't remove all the files completely if following the above procedure.

Are you still able to reproduce this? If you have exact repro steps, please let us know.

Are you able to repro Visual Studio locking up every time you click on solution explorer after uninstalling BI Developer Extensions? Did you have any SSIS or SSAS projects open when this happens?

**Comment by dgosbell** [comment]
Any updates on this?

Like @furmangg  I am unable to reproduce your issue, so one possibility is that this could be a conflict with some other add-in.

But the install location and registration is completely handled by Visual Studio and the VSIX installer which is all Microsoft code. I have seen issues where extensions have somehow got registered twice and therefore need to be uninstalled twice. You can use the [duplicate extension finder](https://github.com/remcoros/DuplicateExtensionFinder) tool to see if this issue is affecting you
