### ISSUE TITLE
Error message when trying to add Tabular folders

### ISSUE THREAD

**Issue by StephenBoyer** [BIDeveloperExtensions/bideveloperextensions#18]
![image](https://user-images.githubusercontent.com/27219941/33434237-b08d3882-d5ac-11e7-99b9-b30ece690e2d.png)

Got this nasty message. I tried re-installing. I am using Visual Studios 2015.

**Comment by furmangg** [comment]
There was a .Commit() method that used to return a list of strings. But somewhere along the way Microsoft changed it to be a void method. That broke our compiled code. I’ve worked around this so it works with old and new versions of this DLL. I'm working with a beta tester to validate my fix then will begin the process of pushing out another release.

https://github.com/BIDeveloperExtensions/bideveloperextensions/commit/1521dcee784d690ece79af2830288504762cfdb5

If you have an urgent need to test a beta build, let me know.

**Comment by Smancer** [comment]
I'd certainly like to test a beta build. I've been resorting to XMLA editing.
Let me know what you need from me.

**Comment by furmangg** [comment]
This is fixed in release 2.1.1. BI Developer Extensions should automatically update or you can go to Tools... Extensions and Updates and then manually install the update.

Thanks for reporting this. I believe the issue was that in older versions of VS2015 SSDT (versions that were installed in the SQL2016 timeframe) it wasn't working because it was looking for a SQL2017 focused DLL. Anyway that's fixed in the following commit:
https://github.com/BIDeveloperExtensions/bideveloperextensions/commit/49fa6265aefa6073b21a92fd9b5d147f2e2fb724
