### ISSUE TITLE
Fresh install BIML Features currently unavailable

### ISSUE THREAD

**Issue by Blinkenn** [BIDeveloperExtensions/bideveloperextensions#23]
I just installed the BI Developer extensions in VS 2015 Professional. After creating an Integration project I get an error when trying to add a BIML file: BIML features are currently unavailable while we wait for Varigence to provide an update to the BIMLEngine component.

**Comment by acb7869** [comment]
I am experiencing the same issue with the same steps to reproduce.
![image](https://user-images.githubusercontent.com/8006404/35589424-6b226982-05c9-11e8-833f-d98c699297cd.png)

**Comment by dgosbell** [comment]
The issue is exactly what the message indicates. The BIML engine that BI Developer Extensions uses was kindly provided by [Varigence](https://www.varigence.com), but needs to be updated to work in Visual Studio 2015 or later. Unfortunately Varigence have not provided an updated BimlEngine and are not responding to any of our repeated attempts to contact them. The BimlEngine is a proprietary component, so we don't have the source and re-implementing it would be a massive multi-year project which is beyond the scope of what would be possible for our small team. However Varigence have released their own BimlExpress add-in that might work for you

**Comment by kshashidhara** [comment]
How to solve this issue ?

**Comment by dgosbell** [comment]
As stated in my previous reply, there is no solution. Varigence appear to not be supporting this project anymore and have not supplied an updated engine that we can use. We are not sure why, they have just stopped replying to any attempts to contact them. Maybe try asking in their forums...
