### ISSUE TITLE
Sortable Package Properties report missing from solution menu

### ISSUE THREAD

**Issue by djgernetzke** [BIDeveloperExtensions/bideveloperextensions#42]
Reinstalled Visual Studio and BIDS Helper on new machine. Sortable Package Properties Report is now missing from solution menu (it is still on project menu). Versions are 12.0.21005.1 of Visual Studio and 2014 Version 1.7.0.0 of BIDS Helper.

**Comment by furmangg** [comment]
This issue is a bit old now and we recommend you move to Visual Studio 2017 where this is working. Visual Studio 2017 is backwards compatible with earlier versions of SQL. 

We don't maintain older versions of BI Developer Extensions for Visual Studio 2013 or lower and we're unlikely to spend much time on Visual Studio 2015 fixes either.
