### ISSUE TITLE
Option for SSAS Display Folders Not Showing

### ISSUE THREAD

**Issue by wmorris20** [BIDeveloperExtensions/bideveloperextensions#45]
I have Visual Studio 2017 15.8.7 and SSDT 15.1.61808.07020.  When navigating to a Tabular Model, I no longer see the option to configure Display Folders.  This was working prior to the update of Visual Studio.

![image](https://user-images.githubusercontent.com/44061094/46807266-2607c300-cd2f-11e8-907e-43b877978988.png)

**Comment by lpawlak95** [comment]
I have same issue

**Comment by furmangg** [comment]
What compatibility level is your database running? If it's 1200 (SQL2016 version or above) then you can use the built-in feature to set the display folders rather than depending on BI Developer Extensions' Tabular Display Folder feature. I'm going to close this issue because I believe you have 1200 or above compatibility level. But let me know if I'm wrong.

If you do have an older compatibility level, please go to Tools... Extensions and Updates and make sure you are running BI Developer Extensions 2.2.0 which was just release in order to fix compatibility with the latest version of SSDT for Visual Studio 2017 (version 15.8.2).
