### ISSUE TITLE
v2.2.1.0 stopped working on VS2017 15.9.7

### ISSUE THREAD

**Issue by tomsts** [BIDeveloperExtensions/bideveloperextensions#55]
Hi,
That issue was recorded some time ago and you released a fix. That comes again.
VS2017 15.9.7
Bids v2.2.1.0
SSDTBI 2019(15.0.1300.59)

Bids Helper version tab shows a big list of errors like Could not load file or assembly 'Microsoft.AnalysisServices.Common.FrontEnd, Version=15.0.0.0 .....
No button to execute MDX script - it gone.
I tried to repair VS2017, but no luck.
pease help. It was working 2 weeks ago...

**Comment by tomsts** [comment]
Same issue was reported and resolved on #43

**Comment by furmangg** [comment]
I have heard that there are some issues with the latest SSDT build for Analysis Services (unrelated to BI Developer Extensions).  We will keep monitoring the situation but rolling back to an earlier build of SSDT like 15.8.2 is probably recommended at this point until the SSDT issues get resolved.

**Comment by tomsts** [comment]
Hi, I had SSDT 15.8.1.
I am trying to uninstall and get 15.9.0. I'll let you know if that helps with a newer version. If not , I will try to downgrade again to 15.8.2.

**Comment by tomsts** [comment]
Closing that case. I uninstalled a previous version of SSDT 15.8.1(MS mentioned that) . And installed the latest stand-alone 15.9.0. No more errors and I can see BIDS button in place. 
Thank you.

**Comment by Iviglious** [comment]
Hi guys,

Thank you for your great contibution with this very usefull extensions.
Do you plan to have a next release to officially support SSDTBI 2019 (SSDT 15.9.0)?
I installed v2.2.1.0, but some functionalities still do not work and it looks like it is because v2.2.1.0 is not for SSDT 15.9.0, but for SSDT 15.8.2.
I'll be waiting eagerly!

Thanks,
Iviglious

**Comment by furmangg** [comment]
Iviglious we have heard from the SSDT team that there are some issues with 15.9.0. So our hope is that the next SSDT release will resolve those issues. Sorry for the inconvenience! If the next release doesn’t resolve it then we will have to see if we can find a workaround. Does that make sense?

**Comment by min-io** [comment]
I had the same issue with the VS 2017 3 weeks ago. I could not find the solution so I have installed SSDT again with its own VS 2017 Shell. It worked for few weeks. It stoped working again. Likely due to Windows Update: https://support.microsoft.com/pl-pl/help/4489899/windows-10-update-kb4489899 or https://support.microsoft.com/pl-pl/help/4480056/january-8-2019-kb4480056.
