### ISSUE TITLE
Entry point not found. "tabular actions editor"

### ISSUE THREAD

**Issue by mhansma** [BIDeveloperExtensions/bideveloperextensions#80]
Hi,

I just installed the bi developer extensions and facing a "entry point was not found" issue. 
When i'm going to the items as "tabular actions editor" or "tabular display folders" in the context menu, the following error shows up.

![image](https://user-images.githubusercontent.com/1673484/66597666-b7f31780-eb9f-11e9-9a9e-ac679d923192.png)

**Version**
![image](https://user-images.githubusercontent.com/1673484/66597951-45cf0280-eba0-11e9-8d1a-e6e295df7bc4.png)

![image](https://user-images.githubusercontent.com/1673484/66598026-6d25cf80-eba0-11e9-84c9-89fc79c22829.png)

**To Reproduce**
1. Install the latest version of the extension tools for VS2017
2. Create a new ssas project (tabular) with version 1103.
3. Right klik on the model.bim
4. Select "tabular actions editor"

Hopefully you can help me out. I like the project very well and using it for years.

**Comment by Oscar876** [comment]
Hi @mhansma 
This issue seems to be caused by an update of the Microsoft Analysis Services Projects extension. What I did to workaround this issue:
1. Uninstall de Microsoft Analysis Services Projects Extension (v 2.9.2)
2. Download the previous version (2.18.19): https://go.microsoft.com/fwlink/?linkid=2106417 and install it. See also https://marketplace.visualstudio.com/items?itemName=ProBITools.MicrosoftAnalysisServicesModelingProjects#overview
3. Open VS **as admin**, locate the extension, and disable "Automatically update this extension".
4. Close and reopen VS.

Hope this helps!

**Comment by furmangg** [comment]
Thanks for posting the workaround @oscar876

Another thing you should immediately do to prevent auto upgrade to the latest version, disable "automatically upgrade this extension" in Tools... Extensions and Updates.

Once we publish a BI Developer Extensions update which is compatible with the latest we will post here.

**Comment by mhansma** [comment]
Thanks a lot. This has solved the issue for us.
